version: '3.9'

networks:
  local-dev:
    external: true

services:
  kenshiapi:
    #platform: linux/amd64 #set to work on ubuntu
    depends_on:
      - redis
      - kenshirabbitmq
    restart: on-failure
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    build:
      context: .
      dockerfile: Kenshi.API/Dockerfile
    image: piotrlanger/kenshiapi
    ports:
      - 3330:3330
      - 3331:3331
    environment:
      - "ASPNETCORE_URLS=http://+:3330"
      - "REDIS_HOST=redis"
    networks:
      - local-dev
        
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
    networks:
      - local-dev
    
  kenshirabbitmq:
    image: rabbitmq:3-management
    ports:
      # AMQP protocol port
      - '5672:5672'
      # HTTP management UI
      - '15672:15672'
    environment:
      HOST_PORT_RABBIT: 5672
      HOST_PORT_RABBIT_MGMT: 15672
    networks:
      - local-dev
    
  kenshigameserver:
    depends_on:
      - redis
    platform: linux/amd64
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    image: piotrlanger/kenshigameserver
    environment:
      - "REDIS_HOST=redis"
    networks:
      - local-dev
    #profiles:
    #  - donotstart
      