version: '3'
services:
  web:
    build: .
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  minikube:
    image: quay.io/kubernetes_incubator/localkube:latest
    ports:
      - "8080:8080"
      - "8443:8443"
